# Generated by Django 4.0.2 on 2022-03-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billed_amount', models.IntegerField()),
                ('allowed_amount', models.IntegerField()),
                ('primary_dx', models.CharField(max_length=7)),
                ('claim_ID', models.IntegerField()),
                ('billing_provider_name', models.CharField(max_length=255)),
                ('billing_provider_ID', models.IntegerField()),
                ('claim_type', models.CharField(max_length=255)),
                ('savings_amount', models.FloatField()),
            ],
        ),
    ]
