# Generated by Django 4.0.2 on 2022-03-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_claims'),
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.IntegerField()),
                ('provider_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='claims',
            name='allowed_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='claims',
            name='billed_amount',
            field=models.FloatField(),
        ),
    ]
