# Generated by Django 4.0.2 on 2022-03-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_providers_alter_claims_allowed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='providers',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='providers',
            name='tax_ID',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='providers',
            name='zipcode',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='providers',
            name='provider_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
